### ISSUE TITLE
Running it only once

### ISSUE THREAD

**Issue by CapitalH** [RickStrahl/jquery-watch#4]
Hi

First of all thanks for this awesome plugin, very helpful.

I had a little bit of hassle figuring out how to only run the watch function callback only once. Could not find a clue how to.

I resolved my problem with a work around, my callback function is now wrapped around an if sentence so that it only watches the class name I want like so:

if (newValue === 'the-class-I-want') {

But again if this specific class is added again the callback function will run which is not something I would want.

Is there some way to accomplish what I'm after?

**Comment by RickStrahl** [comment]
Sorry for the delay in responding. I missed this issue.

I'm not sure I understand. The watcher is designed to indefinitely monitor the watched properties, but it should be pretty straight forward to add some logic into the event handler to shut the watcher down after the first hit.
```javascript
// some element to monitor
var el = $("#notebox");

// hook up the watcher
el.watch({
    // specify CSS styles or attribute names to monitor
    properties: "top,left,opacity,attr_class,prop_innerHTML",

    // callback function when a change is detected
    callback: function(data, i) {
        var propChanged = data.props[i];
        var newValue = data.vals[i];

        var el = this;
        var el$ = $(this);

        // do what you need based on changes
        // or do your own checks

        // now unwatch - delay to ensure ops have run aren't reset
       setTimeout(function() { el$.unwatch(data.id); }, 10);
    }
});
```
